version: '3.8'
services:
  telegram:
    build:
      context: .  
      dockerfile: Dockerfile  
    environment:
      - API_KEY="6281219253:AAGX2omjP_rhPAOkIms-qRl2R7OHmaOA6HQ"
      - DB=mongodb://root:mongo123@mongodb:27017
    depends_on:
      - mongodb 
    volumes:
      - .:/app  
    restart: unless-stopped
    
  mongodb:
    image: mongo:latest
    networks: 
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - ./storage/mongodb:/data/db
    restart: unless-stopped
      
networks:
  mongo-compose-network:
    driver: bridge