version: '3.8'
services:
  telegram:
    build:
      context: .  
      dockerfile: Dockerfile  
    environment:
      - API_KEY=${TELEGRAM_API_TOKEN}
      - DB=mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:27017
    depends_on:
      - mongodb 
    volumes:
      - .:/app  
    restart: unless-stopped
    
  mongodb:
    image: mongo:latest
    networks: 
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage/mongodb:/data/db
    restart: unless-stopped
      
networks:
  mongo-compose-network:
    driver: bridge