version: '3.8'
services:
  telegram:
    build:
      context: .  
      dockerfile: Dockerfile  
    environment:
      - API_KEY=
      - DB=mongodb://root:mongo123@mongodb:27017
    depends_on:
      - mongodb 
    volumes:
      - .:/app  
    restart: unless-stopped
    
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
      
volumes:
  mongo_data: